FROM liquibase/liquibase:latest

ARG DB_HOSTNAME
ARG MIGRATION_PASSWORD

USER root

RUN apt update
RUN apt install -y postgresql-client

COPY ./migration /liquibase/migration
COPY ./postgres/sql /liquibase/migration/sql
COPY ./postgres/init /liquibase/migration/init

RUN chmod +x /liquibase/migration/migrate.sh
RUN chmod +x -R /liquibase/migration/init
USER liquibase

ENTRYPOINT ["/liquibase/migration/migrate.sh"]
