services:

  database:
    extends:
      service: database
      file: compose.yaml

  migration:
    extends:
      service: migration
      file: compose.yaml

  test:
    build:
      context: ./test
      dockerfile: Dockerfile
    environment:
      DB_HOSTNAME: database
      MIGRATION_USER: migration
      MIGRATION_PASSWORD: $MIGRATION_PASSWORD
      ANALYST_USER: analyst
      ANALYST_PASSWORD: $ANALYST_PASSWORD
      IMPORTER_USER: importer
      IMPORTER_PASSWORD: $IMPORTER_PASSWORD
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    depends_on:
      migration:
        condition: service_completed_successfully